<x-public.legal-layout title="Términos y condiciones de sorteos" description="Términos y condiciones aplicables a los sorteos de Tienda Siete Market & Licorería.">
    <section><h2 class="text-xl font-black text-white">1. Identificación del organizador</h2><p class="mt-2">Los sorteos publicados en esta plataforma son organizados por <strong class="text-white">TIENDAS SIETE S.A.C.</strong>, RUC <strong class="text-white">20614107767</strong>. Para consultas relacionadas con un sorteo, escríbenos a <a class="text-cyan-300 underline" href="mailto:sorteos@tiendasiete.com">sorteos@tiendasiete.com</a> o comunícate al <a class="text-cyan-300 underline" href="tel:+51991077380">991 077 380</a>.</p></section>
    <section><h2 class="text-xl font-black text-white">2. Alcance de cada sorteo</h2><p class="mt-2">La fecha, hora, premios, precio de cada opción, descuento del combo y canal de transmisión se publican en la ficha del sorteo correspondiente. Esos datos forman parte de las bases particulares de cada evento y prevalecen para dicho sorteo.</p></section>
    <section><h2 class="text-xl font-black text-white">3. Participación y validación</h2><p class="mt-2">Para participar debes completar los datos solicitados, seleccionar una opción válida y adjuntar el comprobante exigido. La solicitud queda pendiente hasta que TIENDAS SIETE S.A.C. revise el comprobante y valide la ID de transacción cuando corresponda. Un ticket solo se considera activo cuando su estado sea aprobado.</p><p class="mt-2">Las solicitudes con información incompleta, comprobantes no verificables, referencias repetidas, pagos no acreditados o indicios de fraude pueden ser rechazadas. El registro se cierra 30 minutos antes de la hora programada para el sorteo.</p></section>
    <section><h2 class="text-xl font-black text-white">4. Compras y comprobantes</h2><p class="mt-2">Si la modalidad indicada es <strong class="text-white">Compra</strong>, deberá adjuntarse una boleta o factura por una compra mayor a S/ 180.00. Si se elige Yape, Plin o Transferencia, deberá adjuntarse el comprobante de pago. La aprobación no procede hasta completar la verificación administrativa.</p></section>
    <section><h2 class="text-xl font-black text-white">5. Desarrollo y resultados</h2><p class="mt-2">Los participantes deben revisar el canal de transmisión y horario publicados para cada evento. Los resultados se determinan conforme a la mecánica comunicada en el sorteo. TIENDAS SIETE S.A.C. podrá solicitar información razonable para validar la identidad del ganador antes de entregar un premio.</p></section>
    <section><h2 class="text-xl font-black text-white">6. Responsabilidad y cambios</h2><p class="mt-2">TIENDAS SIETE S.A.C. podrá suspender, reprogramar o modificar un sorteo cuando exista una causa justificada, caso fortuito, fuerza mayor, error material o necesidad de proteger la transparencia del evento. Cualquier cambio relevante será comunicado en la ficha del sorteo o por los canales de contacto registrados.</p></section>
    <section><h2 class="text-xl font-black text-white">7. Contacto y reclamos</h2><p class="mt-2">Puedes presentar una consulta o reclamo escribiendo a <a class="text-cyan-300 underline" href="mailto:sorteos@tiendasiete.com">sorteos@tiendasiete.com</a>, indicando tu nombre, DNI, sorteo y detalle del caso. Estos términos deben revisarse junto con la información particular publicada para cada evento.</p></section>
</x-public.legal-layout>
